// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlwVodjR7hJuM4i0hhOnLpF13JP-gfmQw',
    appId: '1:408198024504:web:90ba46e46b9d011c56c5cd',
    messagingSenderId: '408198024504',
    projectId: 'hostel-management-4cb90',
    authDomain: 'hostel-management-4cb90.firebaseapp.com',
    storageBucket: 'hostel-management-4cb90.firebasestorage.app',
    measurementId: 'G-F4DNJRGL03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SewxkUCL13L9-GzPfV3lls-AAZa0ffI',
    appId: '1:408198024504:android:04390ba25a667d1556c5cd',
    messagingSenderId: '408198024504',
    projectId: 'hostel-management-4cb90',
    storageBucket: 'hostel-management-4cb90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4a5nvSg2uSXi8f5g4EJNPkbIt5qDtAIU',
    appId: '1:408198024504:ios:ee491367401a0e4256c5cd',
    messagingSenderId: '408198024504',
    projectId: 'hostel-management-4cb90',
    storageBucket: 'hostel-management-4cb90.firebasestorage.app',
    iosBundleId: 'com.example.minipro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4a5nvSg2uSXi8f5g4EJNPkbIt5qDtAIU',
    appId: '1:408198024504:ios:ee491367401a0e4256c5cd',
    messagingSenderId: '408198024504',
    projectId: 'hostel-management-4cb90',
    storageBucket: 'hostel-management-4cb90.firebasestorage.app',
    iosBundleId: 'com.example.minipro',
  );
}
